name: PR pre-release version

on:
  issue_comment:
    types: [created, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish new debug version
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/publish')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Restore cached node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Publish new pre-release version
        run: npx semantic-release@17.4.7 --debug --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: "early" # Pretend we are in the early branch to pre-publish the version
