name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Test
        run: npm run format:check
