name: Version

on:
  push:
    branches:
      - conf-fix

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        run: npx semantic-release@17.4.7 --branches conf-fix --dry-run --debug --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_PR_NUMBER: 14
          GITHUB_REF: conf-fix
          GITHUB_EVENT_NAME: test
